service: uyd
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ${file(./conf/serverless.yml):AWS_REGION}
  environment:
    OPENAI_API_KEY: ${file(./conf/serverless.yml):OPENAI_API_KEY}

functions:
  dream-analyser:
    handler: handler.analyser

plugins:
  - serverless-esbuild

resources:
  Resources:
    dreamsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dreams
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1