service: uyd
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ${file(./conf/serverless.yml):AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb: DescribeTable
        - dynamodb: Query
        - dynamodb: Scan
        - dynamodb: GetItem
        - dynamodb: PutItem
        - dynamodb: UpdateItem
        - dynamodb: DeleteItem
      Resource:
        - Fn::GetAtt": [ dreamsTable, Arn ]
  environment:
    TABLE_NAME:
      Ref: dreamsTable
    OPENAI_API_KEY: ${file(./conf/serverless.yml):OPENAI_API_KEY}

functions:
  dream-analyser:
    handler: handler.analyser

plugins:
  - serverless-esbuild

resources:
  Resources:
    dreamsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dreams
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1